In [ ]:
import pandas as pd
df = pd.read_csv("medical_dataset.csv")
df.head()

Age  Weight_kg  Height_cm   BMI  Blood_Pressure_Systolic  \
0   80       87.1      197.0  23.5                      111   
1   34      107.1      186.6  28.8                      157   
2   50       84.9      158.1  20.5                      158   
3   46       54.7      159.4  29.8                      126   
4   30       78.4      186.5  30.7                      138   

   Blood_Pressure_Diastolic  Cholesterol_mg_dL  Blood_Sugar_mg_dL  Gender  \
0                        63                171                 95    Male   
1                        94                188                144  Female   
2                       119                169                177    Male   
3                       107                190                112    Male   
4                       115                297                 77    Male   

       Diagnosis  
0        Healthy  
1       Diabetes  
2       Diabetes  
3  Heart Disease  
4        Healthy

In [ ]:
df.isnull().sum()

Age                         0
Weight_kg                   0
Height_cm                   0
BMI                         0
Blood_Pressure_Systolic     0
Blood_Pressure_Diastolic    0
Cholesterol_mg_dL           0
Blood_Sugar_mg_dL           0
Gender                      0
Diagnosis                   0
dtype: int64

In [3]:
df.shape

(500, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Age                       500 non-null    int64  
 1   Weight_kg                 500 non-null    float64
 2   Height_cm                 500 non-null    float64
 3   BMI                       500 non-null    float64
 4   Blood_Pressure_Systolic   500 non-null    int64  
 5   Blood_Pressure_Diastolic  500 non-null    int64  
 6   Cholesterol_mg_dL         500 non-null    int64  
 7   Blood_Sugar_mg_dL         500 non-null    int64  
 8   Gender                    500 non-null    object 
 9   Diagnosis                 500 non-null    object 
dtypes: float64(3), int64(5), object(2)
memory usage: 39.2+ KB


In [5]:
df.describe()

Age   Weight_kg   Height_cm         BMI  \
count  500.000000  500.000000  500.000000  500.000000   
mean    52.510000   84.929800  174.689800   26.403600   
std     21.094166   20.343186   14.124784    5.003585   
min     18.000000   50.000000  150.000000   18.000000   
25%     34.000000   67.675000  162.150000   21.975000   
50%     52.000000   86.050000  175.200000   26.250000   
75%     70.250000  102.025000  187.125000   30.800000   
max     89.000000  120.000000  199.800000   35.000000   

       Blood_Pressure_Systolic  Blood_Pressure_Diastolic  Cholesterol_mg_dL  \
count               500.000000                500.000000         500.000000   
mean                133.596000                 89.580000         227.246000   
std                  25.647932                 17.907679          42.224439   
min                  90.000000                 60.000000         150.000000   
25%                 111.000000                 75.000000         193.750000   
50%                 134.000000                 88.000000         225.000000   
75%                 155.250000                106.000000         263.250000   
max                 179.000000                119.000000         299.000000   

       Blood_Sugar_mg_dL  
count         500.000000  
mean          136.306000  
std            38.361277  
min            70.000000  
25%           101.000000  
50%           137.500000  
75%           172.000000  
max           199.000000

In [6]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
d = df.select_dtypes(include=['object'])
d

Gender      Diagnosis
0      Male        Healthy
1    Female       Diabetes
2      Male       Diabetes
3      Male  Heart Disease
4      Male        Healthy
..      ...            ...
495    Male       Diabetes
496    Male       Diabetes
497  Female  Heart Disease
498    Male  Heart Disease
499  Female        Healthy

[500 rows x 2 columns]

In [7]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Gender     500 non-null    object
 1   Diagnosis  500 non-null    object
dtypes: object(2)
memory usage: 7.9+ KB


In [8]:
encode = ohe.fit_transform(d)
print(encode)
encoded_labels = ohe.fit_transform(d).toarray()
print(encoded_labels)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1000 stored elements and shape (500, 6)>
  Coords	Values
  (0, 1)	1.0
  (0, 3)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (2, 2)	1.0
  (3, 1)	1.0
  (3, 4)	1.0
  (4, 1)	1.0
  (4, 3)	1.0
  (5, 0)	1.0
  (5, 2)	1.0
  (6, 1)	1.0
  (6, 4)	1.0
  (7, 1)	1.0
  (7, 3)	1.0
  (8, 1)	1.0
  (8, 4)	1.0
  (9, 0)	1.0
  (9, 5)	1.0
  (10, 1)	1.0
  (10, 2)	1.0
  (11, 1)	1.0
  (11, 5)	1.0
  (12, 1)	1.0
  :	:
  (487, 4)	1.0
  (488, 1)	1.0
  (488, 5)	1.0
  (489, 1)	1.0
  (489, 4)	1.0
  (490, 0)	1.0
  (490, 5)	1.0
  (491, 1)	1.0
  (491, 4)	1.0
  (492, 1)	1.0
  (492, 5)	1.0
  (493, 0)	1.0
  (493, 4)	1.0
  (494, 1)	1.0
  (494, 4)	1.0
  (495, 1)	1.0
  (495, 2)	1.0
  (496, 1)	1.0
  (496, 2)	1.0
  (497, 0)	1.0
  (497, 4)	1.0
  (498, 1)	1.0
  (498, 4)	1.0
  (499, 0)	1.0
  (499, 3)	1.0
[[0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0.]]


In [9]:
df_encoded = pd.DataFrame(encoded_labels)
df_encoded

0    1    2    3    4    5
0    0.0  1.0  0.0  1.0  0.0  0.0
1    1.0  0.0  1.0  0.0  0.0  0.0
2    0.0  1.0  1.0  0.0  0.0  0.0
3    0.0  1.0  0.0  0.0  1.0  0.0
4    0.0  1.0  0.0  1.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...
495  0.0  1.0  1.0  0.0  0.0  0.0
496  0.0  1.0  1.0  0.0  0.0  0.0
497  1.0  0.0  0.0  0.0  1.0  0.0
498  0.0  1.0  0.0  0.0  1.0  0.0
499  1.0  0.0  0.0  1.0  0.0  0.0

[500 rows x 6 columns]

In [10]:
df.drop(columns=d.columns,inplace=True)
df

Age  Weight_kg  Height_cm   BMI  Blood_Pressure_Systolic  \
0     80       87.1      197.0  23.5                      111   
1     34      107.1      186.6  28.8                      157   
2     50       84.9      158.1  20.5                      158   
3     46       54.7      159.4  29.8                      126   
4     30       78.4      186.5  30.7                      138   
..   ...        ...        ...   ...                      ...   
495   75       74.0      152.6  19.5                      100   
496   46       87.3      174.3  28.3                      117   
497   54       58.8      180.0  20.6                      159   
498   87       59.3      180.1  18.5                      130   
499   35       60.0      151.1  34.5                      105   

     Blood_Pressure_Diastolic  Cholesterol_mg_dL  Blood_Sugar_mg_dL  
0                          63                171                 95  
1                          94                188                144  
2                         119                169                177  
3                         107                190                112  
4                         115                297                 77  
..                        ...                ...                ...  
495                        75                162                 98  
496                        61                215                 94  
497                       119                186                139  
498                        83                215                132  
499                        69                185                199  

[500 rows x 8 columns]

In [11]:
df1 = pd.concat([df_encoded,df],ignore_index=True, axis=1)
df1

0    1    2    3    4    5   6      7      8     9    10   11   12   13
0    0.0  1.0  0.0  1.0  0.0  0.0  80   87.1  197.0  23.5  111   63  171   95
1    1.0  0.0  1.0  0.0  0.0  0.0  34  107.1  186.6  28.8  157   94  188  144
2    0.0  1.0  1.0  0.0  0.0  0.0  50   84.9  158.1  20.5  158  119  169  177
3    0.0  1.0  0.0  0.0  1.0  0.0  46   54.7  159.4  29.8  126  107  190  112
4    0.0  1.0  0.0  1.0  0.0  0.0  30   78.4  186.5  30.7  138  115  297   77
..   ...  ...  ...  ...  ...  ...  ..    ...    ...   ...  ...  ...  ...  ...
495  0.0  1.0  1.0  0.0  0.0  0.0  75   74.0  152.6  19.5  100   75  162   98
496  0.0  1.0  1.0  0.0  0.0  0.0  46   87.3  174.3  28.3  117   61  215   94
497  1.0  0.0  0.0  0.0  1.0  0.0  54   58.8  180.0  20.6  159  119  186  139
498  0.0  1.0  0.0  0.0  1.0  0.0  87   59.3  180.1  18.5  130   83  215  132
499  1.0  0.0  0.0  1.0  0.0  0.0  35   60.0  151.1  34.5  105   69  185  199

[500 rows x 14 columns]

In [12]:
df1.shape

(500, 14)

In [13]:
X = df1.iloc[:,:-1]
y = df1.iloc[:,-1]
print(X)
print(y)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1, random_state=42)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

      0    1    2    3    4    5   6      7      8     9    10   11   12
0    0.0  1.0  0.0  1.0  0.0  0.0  80   87.1  197.0  23.5  111   63  171
1    1.0  0.0  1.0  0.0  0.0  0.0  34  107.1  186.6  28.8  157   94  188
2    0.0  1.0  1.0  0.0  0.0  0.0  50   84.9  158.1  20.5  158  119  169
3    0.0  1.0  0.0  0.0  1.0  0.0  46   54.7  159.4  29.8  126  107  190
4    0.0  1.0  0.0  1.0  0.0  0.0  30   78.4  186.5  30.7  138  115  297
..   ...  ...  ...  ...  ...  ...  ..    ...    ...   ...  ...  ...  ...
495  0.0  1.0  1.0  0.0  0.0  0.0  75   74.0  152.6  19.5  100   75  162
496  0.0  1.0  1.0  0.0  0.0  0.0  46   87.3  174.3  28.3  117   61  215
497  1.0  0.0  0.0  0.0  1.0  0.0  54   58.8  180.0  20.6  159  119  186
498  0.0  1.0  0.0  0.0  1.0  0.0  87   59.3  180.1  18.5  130   83  215
499  1.0  0.0  0.0  1.0  0.0  0.0  35   60.0  151.1  34.5  105   69  185

[500 rows x 13 columns]
0       95
1      144
2      177
3      112
4       77
      ... 
495     98
496     94
497    139


LinearRegression()

In [14]:
lm.coef_

array([ 2.37844489, -2.37844489,  1.20247166,  3.53329263, -8.30372932,
        3.56796502,  0.06278803,  0.0825506 , -0.26366797, -0.09057368,
        0.02012234,  0.05746792,  0.02657293])

In [15]:
lm.intercept_

np.float64(161.30776063332934)