In [239]:
import pandas as pd
df = pd.read_csv("datasets/one_hot.csv")
df.head()

name     sex degree  experience  salary
0  aaa  female     ug           2   10000
1  bbb    male     pg           3  200000
2  ccc    male     ug           4   10000
3  ddd  female     pg           5   10000
4  eee    male     ug           3   20000

In [240]:
df.isnull().sum()

name          0
sex           0
degree        0
experience    0
salary        0
dtype: int64

In [241]:
df.shape

(5, 5)

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        5 non-null      object
 1   sex         5 non-null      object
 2   degree      5 non-null      object
 3   experience  5 non-null      int64 
 4   salary      5 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes


In [243]:
df.drop(columns=['name'],inplace=True) # Makes the change directly to df without needing to reassign it.

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   sex         5 non-null      object
 1   degree      5 non-null      object
 2   experience  5 non-null      int64 
 3   salary      5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes


In [245]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
d = df.select_dtypes(include=['object'])
d

sex degree
0  female     ug
1    male     pg
2    male     ug
3  female     pg
4    male     ug

In [246]:
encode = ohe.fit_transform(d)
print(encode)
encoded_labels = ohe.fit_transform(d).toarray()
print(encoded_labels)

  (0, 0)	1.0
  (0, 3)	1.0
  (1, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (2, 3)	1.0
  (3, 0)	1.0
  (3, 2)	1.0
  (4, 1)	1.0
  (4, 3)	1.0
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


In [247]:
df1 = pd.DataFrame(encoded_labels)

In [248]:
df1.shape

(5, 4)

In [249]:
X = df1.iloc[:,:-1]
y = df1.iloc[:,-1]
print(X)
print(y)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1, random_state=42)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

     0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  1.0
2  0.0  1.0  0.0
3  1.0  0.0  1.0
4  0.0  1.0  0.0
0    1.0
1    0.0
2    1.0
3    0.0
4    1.0
Name: 3, dtype: float64


LinearRegression()

In [250]:
lm.coef_

array([-4.96506831e-17,  5.55111512e-17, -1.00000000e+00])

In [251]:
lm.intercept_

0.9999999999999999

## With Own dataset

In [252]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [253]:
df = pd.read_csv("datasets/car.csv")
df.head()

Car Model  Mileage  Sell Price  Age
0      Audi    87000       76543    2
1      Audi    67000       58760    3
2      Audi    45000       27650    4
3    BMW X5    78000       66540    7
4    BMW X5    67000       56450    1

In [254]:
df.shape

(22, 4)

In [255]:
df.isnull().sum()

Car Model     0
Mileage       0
Sell Price    0
Age           0
dtype: int64

In [256]:
x = df.drop(columns=["Sell Price"])
y = df['Sell Price']

In [257]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [258]:
encoded_labels = ohe.fit_transform(df[['Car Model']]).toarray()
print(encoded_labels)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [259]:
dum = pd.DataFrame(encoded_labels)
dum.head()


0    1    2    3
0  1.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0
2  1.0  0.0  0.0  0.0
3  0.0  1.0  0.0  0.0
4  0.0  1.0  0.0  0.0

In [260]:
# dum = pd.get_dummies(x["Car Model"])
# dum.head()

In [261]:
combained = pd.concat([x,dum], axis = 1)
combained.head()

Car Model  Mileage  Age    0    1    2    3
0      Audi    87000    2  1.0  0.0  0.0  0.0
1      Audi    67000    3  1.0  0.0  0.0  0.0
2      Audi    45000    4  1.0  0.0  0.0  0.0
3    BMW X5    78000    7  0.0  1.0  0.0  0.0
4    BMW X5    67000    1  0.0  1.0  0.0  0.0

In [262]:
final_x = combained.drop(columns=["Car Model","Age"])
final_x

Mileage    0    1    2    3
0     87000  1.0  0.0  0.0  0.0
1     67000  1.0  0.0  0.0  0.0
2     45000  1.0  0.0  0.0  0.0
3     78000  0.0  1.0  0.0  0.0
4     67000  0.0  1.0  0.0  0.0
5     87500  0.0  0.0  0.0  1.0
6     87000  0.0  1.0  0.0  0.0
7     47600  0.0  1.0  0.0  0.0
8     87650  0.0  1.0  0.0  0.0
9     78650  1.0  0.0  0.0  0.0
10    89760  1.0  0.0  0.0  0.0
11    23000  1.0  0.0  0.0  0.0
12    43500  1.0  0.0  0.0  0.0
13    65900  0.0  0.0  1.0  0.0
14    76000  0.0  0.0  1.0  0.0
15    76500  0.0  0.0  1.0  0.0
16    76500  0.0  0.0  1.0  0.0
17    87650  0.0  0.0  1.0  0.0
18    76230  0.0  0.0  0.0  1.0
19    65470  0.0  0.0  0.0  1.0
20    65430  0.0  0.0  0.0  1.0
21    98600  0.0  0.0  0.0  1.0

In [263]:
print(final_x.columns)

Index(['Mileage', 0, 1, 2, 3], dtype='object')


In [264]:
# Convert all column names to strings to avoid mixed type error
final_x.columns = final_x.columns.astype(str)
print(final_x.columns)
from sklearn.model_selection import train_test_split

Index(['Mileage', '0', '1', '2', '3'], dtype='object')


In [265]:
print(final_x.columns)  # Verify column names are strings
x_train,x_test,y_train,y_test = train_test_split(final_x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(y_train.shape)

Index(['Mileage', '0', '1', '2', '3'], dtype='object')
(17, 5)
(17,)


In [266]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [267]:
y_pred = model.predict(x_test)

In [268]:
from sklearn.metrics import r2_score, mean_absolute_error
print(f"r2 score is {r2_score(y_test,y_pred)}")
print(f"mean_absolute_error is {mean_absolute_error(y_test,y_pred)}")

r2 score is 0.9723770284249046
mean_absolute_error is 1144.1913142801598
