## **COPY AND VIEW IN ARRAY**

In [ ]:
#Illustration of copy
import numpy as np
arr=np.array([1,2,3,4,5])
x = arr.copy()
arr[0]= 42 #does not affect the original array
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#Illustration of view
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42   #change in a original array
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31    #change in a view
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]
