**Reshaping array using reshape(),flatten() and ravel()**

In [7]:
#Reshaping array from 1-d to 2-d
import numpy as np
arr=np.array([11,22,33,44,55,66,77,88,99,111])
#using reshape()
newarr = arr.reshape(2,5)
print(newarr)

[[ 11  22  33  44  55]
 [ 66  77  88  99 111]]


In [9]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# Reshape From 2-D to 1-D
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
newarr1 = arr.reshape(1,8)   # returns 2-D array with 1 row and 8 coulmns
newarr2 = arr.reshape(-2028)
print(newarr1)
print(newarr2)
print(newarr1.shape)
print(newarr2.shape)

[[1 2 3 4 5 6 7 8]]
[1 2 3 4 5 6 7 8]
(1, 8)
(8,)


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]])
print(arr)
print(arr.shape)
newarr = arr.reshape(-1) # 3-d to 1-d
print(newarr)
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
pri
arr_3d = arr.reshape(2, 3, 4)

print(arr_3d)