In [1]:
#slicing 1-d array
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1:3])
print(arr[-4:-2])
print(arr[::2])

[2 3]
[1 2]
[1 3]


In [4]:
#slicing 2-d array
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr[:, 1:4])
print(arr[0, 1:4])
print(arr[1, 1:-1])
print(arr[0, 1:-1])
print(arr[2, :])
print(arr[1, :])
print(arr[0:2, 2])
print(arr[0:2, 2:4])
print(arr[::-1, :])
print(arr[:, ::-1])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
[2 3 4]
[7 8 9]
[2 3 4]
[11 12 13 14 15]
[ 6  7  8  9 10]
[3 8]
[[3 4]
 [8 9]]
[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
